name: Deploy to UAT Sandbox
run-name: ${{ github.actor }} is running the Github Actions 🚀

on:
  pull_request:
    types: [closed]
    branches:
      - uat
    paths:
      - 'force-app/**'

jobs:
  build-and-deploy: 
    name: Deploy to UAT
    uses: "./.github/workflows/template.yml"
    permissions:
      contents: read
      security-events: write
      actions: read
    with:
      environment: uat
    secrets: inherit