name: Production Pipeline
run-name: Amit Singh is running the Github Actions 🚀
## Pipeline will be running mainly on 2 events most of time 
### push, pull_request
on: [push, pull_request]

jobs:
  build-and-deploy: ## Name of the Job
    runs-on: ubuntu-latest ## Github Hosted [Self Hosted]
    ## Example - Develop an Apex trigger to count the total no of contacts under an account [job]
    ## Example#2 - Deploy all the Apex Triggers and Classes developed as part of US-8834 [job]
    steps:
      - run: echo "This is my first Job"
        name: "First Job Message"
  clean-up:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is my second Job"
        name: "Print Message"