name: Dev Pipeline
run-name: ${{ github.actor }} is running the Github Actions 🚀
## Pipeline will be running mainly on 2 events most of the time 
### push, pull_request
on: [push, pull_request]

jobs:
  build-and-deploy: ## Name of the Job
    runs-on: ubuntu-latest ## Github Hosted [Self Hosted]
    ## Example - Develop an Apex trigger to count the total no of contacts under an account [job]
    ## Example#2 - Deploy all the Apex Triggers and Classes developed as part of US-8834 [job]
    steps:
      - run: echo "This is my first Job"
        name: "First Job Message"
      - name: Checkout Code
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      - name: npm install
        run: npm install
        ## Install Saleforce CLI
      - name: Install Salesforce CLI
        run: npm install @salesforce/cli --global 
        ## Login OR Connect to Salesforce using JWT Token 
          ### 1. Connected Application and configure the User
                ## SSL Ceriticate [OPENSSL]  

      - name: Authorize with Salesforce org
        run: sf org login jwt --username deploymentuser@course.com.prod --jwt-key-file assets/server.key --client-id 3MVG9H_KVs6V9LiM7Y7c5ITSQXsdScQK0GviHUXJEQKzM.gX4Ui1yELw1hBDT86XI99Udx0I2CWwqhOWKxxrx --set-default --alias ci-org --instance-url https://login.salesforce.com
      - name: Print User Information
        run: sf org display user -o ci-org
  clean-up:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is my second Job"
        name: "Print Message"