name: Dev Pipeline
run-name: ${{ github.actor }} is running the Github Actions
## Pipeline will be running mainly on 2 events most of time
## Push, Pull request
on: [push, pull_request]

jobs:
  build-and-deploy: ## Name of the Job
    runs-on: ubuntu-latest ## Github Hosted [Self Hosted]
    ## Example - Develop an Apex Trigger to count the total no of contacts under an account [job]
    ## Example - Deploy all the Apex Triggers and Classes developed as part of US-8834 [job]
    steps:
      - run: echo "This is my first job"
        name: "First Job Message"
      - name: Checkout Code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
        ## Install Salesforce CLI
      - name: Install Salesforce CLI
        run: npm install @salesforce/cli --global
        ## Login OR Connect to Salesforce using JWT Token
        #### 1. Connected Application and configure the user
        ## SSL Certificate [OpenSSL]

      - name: Authorize with Salesforce org
        run: sf org login jwt --username kolliparasai987-kspr@force.com --jwt-key-file assets/server.key --client-id 3MVG9RGN2EqkAxhLeFSmxm6zvVqqXyWpXS8VYNvUw.NMxJLjhiGPxyosUdTDzhLu46GH031_Q3C86UZvsl1zR --set-default --alias ci-org --instance-url https://login.salesforce.com
      - name: Print User Information
        run: sf org display user -o ci-org
  clean-up:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is my second job"
        name: "Print Message"