name: Code Validation
run-name: ${{ github.actor }} is running the Github Actions 🚀

on:
  push:
    paths:
      - 'force-app/**'
    branches:
      - feature/*
      - bugfix/*
      - hotfix/*

jobs:
  build-and-deploy: 
    name: Deploy using Reusable Template
    uses: "./.github/workflows/template.yml"